# === Mapping ticker -> sector (Thai + English) ===

ticker_sector = {
    "ADVANC": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "AEONTS": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "AHC": ("การแพทย์", "Healthcare Services"),
    "AIT": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "ALUCON": ("บรรจุภัณฑ์", "Packaging"),
    "AOT": ("ขนส่งและโลจิสติกส์", "Transportation & Logistics"),
    "AP": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "ASIA": ("บริการ", "Services"),
    "ASK": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "AYUD": ("ประกันภัยและประกันชีวิต", "Insurance"),
    "BAFS": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "BAY": ("ธนาคาร", "Banking"),
    "BBL": ("ธนาคาร", "Banking"),
    "BCH": ("การแพทย์", "Healthcare Services"),
    "BCP": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "BCT": ("เหล็กและโลหะ", "Steel"),
    "BDMS": ("การแพทย์", "Healthcare Services"),
    "BH": ("การแพทย์", "Healthcare Services"),
    "BJC": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "BOL": ("สื่อและสิ่งพิมพ์", "Media & Publishing"),
    "CENTEL": ("ท่องเที่ยวและสันทนาการ", "Tourism & Leisure"),
    "CMR": ("บริการ", "Services"),
    "CPALL": ("พาณิชย์", "Commerce"),
    "CPF": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "CPI": ("วัสดุก่อสร้าง", "Construction Materials"),
    "CPN": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "CPNREIT": ("กองทุนรวมอสังหาริมทรัพย์", "Property Funds & REITs"),
    "CSC": ("บริการรับเหมาก่อสร้าง", "Construction Services"),
    "DCC": ("วัสดุก่อสร้าง", "Construction Materials"),
    "DELTA": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "DRT": ("ยานยนต์", "Automotive"),
    "DUSIT": ("ท่องเที่ยวและสันทนาการ", "Tourism & Leisure"),
    "EGCO": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "GC": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "GFPT": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "HFT": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "HMPRO": ("พาณิชย์", "Commerce"),
    "HTC": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "ICC": ("สินค้าอุปโภคบริโภค", "Consumer Products"),
    "ILINK": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "IRC": ("ยานยนต์", "Automotive"),
    "JAS": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "JCT": ("อุตสาหกรรมเหล็ก/โลหะ", "Steel"),
    "KBANK": ("ธนาคาร", "Banking"),
    "KCAR": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "KCE": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "KGI": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "KKP": ("ธนาคาร", "Banking"),
    "KTB": ("ธนาคาร", "Banking"),
    "KTC": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "KYE": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "L&E": ("สินค้าอุตสาหกรรม", "Industrials"),
    "LANNA": ("เหมืองแร่", "Mining"),
    "LEE": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "LST": ("วัสดุก่อสร้าง", "Construction Materials"),
    "MBK": ("พาณิชย์", "Commerce"),
    "M-CHAI": ("อสังหาเชิงพาณิชย์", "Commercial Property"),
    "MCS": ("เหล็กและโลหะ", "Steel"),
    "METCO": ("เหล็กและโลหะ", "Steel"),
    "MFC": ("กองทุนรวม", "Property Funds & REITs"),
    "MFEC": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "MINT": ("ท่องเที่ยวและสันทนาการ", "Tourism & Leisure"),
    "MNIT": ("การแพทย์", "Healthcare Services"),
    "MODERN": ("บริการ", "Services"),
    "MSC": ("เทคโนโลยีสารสนเทศและการสื่อสาร", "Information & Communication Technology"),
    "MTI": ("ประกันภัยและประกันชีวิต", "Insurance"),
    "NOBLE": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "NOVA": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "NTV": ("ขนส่งและโลจิสติกส์", "Transportation & Logistics"),
    "PATO": ("สินค้าอุตสาหกรรม", "Industrials"),
    "PB": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "PRAKIT": ("สื่อและสิ่งพิมพ์", "Media & Publishing"),
    "PREB": ("บริการรับเหมาก่อสร้าง", "Construction Services"),
    "PRG": ("ร้านอาหาร", "Restaurant & Retail Food"),
    "PTT": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "PTTEP": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "PYLON": ("บริการรับเหมาก่อสร้าง", "Construction Services"),
    "QH": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "RAM": ("การแพทย์", "Healthcare Services"),
    "RATCH": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "S&J": ("สินค้าอุปโภคบริโภค", "Consumer Products"),
    "SAUCE": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "SCP": ("เหล็กและโลหะ", "Steel"),
    "SHANG": ("ท่องเที่ยวและสันทนาการ", "Tourism & Leisure"),
    "SIRI": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "SIS": ("พาณิชย์", "Commerce"),
    "SITHAI": ("อุตสาหกรรมพลาสติก", "Plastic Industry"),
    "SKR": ("การแพทย์", "Healthcare Services"),
    "SMIT": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "SNC": ("ยานยนต์", "Automotive"),
    "SNP": ("ร้านอาหาร", "Restaurant & Retail Food"),
    "SORKON": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "SPALI": ("พัฒนาอสังหาริมทรัพย์", "Property Development"),
    "SPC": ("พาณิชย์", "Commerce"),
    "SPCG": ("พลังงานและสาธารณูปโภค", "Energy & Utilities"),
    "SPG": ("สินค้าอุตสาหกรรม", "Industrials"),
    "SPI": ("บริการเฉพาะกิจ", "Professional Services"),
    "SSF": ("สินค้าอุตสาหกรรม", "Industrials"),
    "SSSC": ("เหล็กและโลหะ", "Steel"),
    "STANLY": ("ยานยนต์", "Automotive"),
    "STPI": ("บริการรับเหมาก่อสร้าง", "Construction Services"),
    "SUC": ("วัสดุก่อสร้าง", "Construction Materials"),
    "SVI": ("ชิ้นส่วนอิเล็กทรอนิกส์", "Electronic Components"),
    "SWC": ("สินค้าอุปโภคบริโภค", "Consumer Products"),
    "TASCO": ("วัสดุก่อสร้าง", "Construction Materials"),
    "TC": ("สินค้าอุตสาหกรรม", "Industrials"),
    "TCAP": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "TFMAMA": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "THANI": ("เงินทุนและสินเชื่อ", "Finance & Credit"),
    "THIP": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "TIF1": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "TISCO": ("เงินทุนและหลักทรัพย์", "Finance & Securities"),
    "TKS": ("สื่อและสิ่งพิมพ์", "Media & Publishing"),
    "TMD": ("สินค้าอุตสาหกรรม", "Industrials"),
    "TMT": ("วัสดุก่อสร้าง", "Construction Materials"),
    "TNH": ("การแพทย์", "Healthcare Services"),
    "TPAC": ("บรรจุภัณฑ์", "Packaging"),
    "TSC": ("บริการรับเหมาก่อสร้าง", "Construction Services"),
    "TSTE": ("เครื่องดื่ม", "Food & Beverage"),
    "TU": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "TVO": ("อาหารเกษตร", "Agribusiness"),
    "TWPC": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "UP": ("พาณิชย์", "Commerce"),
    "UPF": ("บริการ", "Services"),
    "UPOIC": ("อาหารเกษตร", "Agribusiness"),
    "UTP": ("อุตสาหกรรมกระดาษ", "Paper Industry"),
    "UVAN": ("อาหารและเครื่องดื่ม", "Food & Beverage"),
    "VIBHA": ("การแพทย์", "Healthcare Services"),
}

# === Helper Function ===
def get_sector(symbol):
    symbol = symbol.replace(".BK","").upper()
    return ticker_sector.get(symbol, ("ไม่พบข้อมูล", "Not Found"))
